# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Testing Dev

on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 7.2
            extensions: mbstring, intl
            ini-values: post_max_size=256M, log_errors=1
            coverage: pcov
            tools: pecl
        - name: PHPUnit tests
          uses: php-actions/phpunit@v3
          with:
            configuration: test/phpunit.xml
            memory_limit: 256M
